### ISSUE TITLE
Cannot test error reporting

### ISSUE THREAD

**Issue by xzyfer** [sass/sass-spec#136]
As it stands it's not possible to assert an error condition. i.e `error on duplicate keys in maps `  https://github.com/sass/libsass/issues/628

There are cases where a spec like the following should be possible https://github.com/sass/sass-spec/pull/133/files.

Maybe we can redirect error output in the assertion some how. Thoughts? 

/cc @lunelson @hcatlin

**Comment by chriseppstein** [comment]
Sass has an output format for errors that results in CSS output. IMO, Errors should be compared using that output. We also need to track warnings. For this, I think there should be a file `output.stderr`. If not present then any stderr output would be a failure, and if present, the stderr output would have to match.

**Comment by chriseppstein** [comment]
I don't think an unexpected output is required. Simply making an output file that is empty should suffice.

**Comment by HugoGiraudel** [comment]
>  Errors should be compared using that output

This.

**Comment by mgreter** [comment]
@chriseppstein I used pretty much the same approach for my local test runner. But IMHO there could a use case for having `output.css` and `output.err` present. Basically it just means to test stdout and stderr and nothing forbids it to output on both (like i.e. emitting warnings). I made both files optional which simply means that I expect an empty stream. There is no difference in having the file empty or not existing (altough output.css could be used to trigger the test in the first place).

**Comment by am11** [comment]
Perhaps it would be a good idea to replace Ruby minitest gem with something like [C++ minitest](http://www.codeproject.com/Articles/9757/Minimal-unit-test-library-for-C) to have more native control over memory and std streams to tests other aspects of libsass, beyond Sass code-generation. This way we can also write independent tests for source-map and external plugins in future. One thing we would probably have to write is the coverage part, for which we can hook native lcov or gcov.

**Comment by saper** [comment]
Before we rewrite a whole thing, I just had a look at the ruby code with my basic understanding of the language and found the following:

* a [test case](https://github.com/sass/sass-spec/blob/6d38353b04e22a044eaab6f6e9bebaeeb5c5f7e4/lib/sass_spec/test_case.rb#L45) reports standard output, cleaned standard output, standard error and compile error and the status code resulting from the compilation
* a [runner](https://github.com/sass/sass-spec/blob/6d38353b04e22a044eaab6f6e9bebaeeb5c5f7e4/lib/sass_spec/runner.rb#L44-L45) just loads few files that describe the expected values:
  * "expected standard output"
  *"expected clean standard output" (optional)
  * applicable output style
   and feeds them to the test case
* a [comparator](https://github.com/sass/sass-spec/blob/6d38353b04e22a044eaab6f6e9bebaeeb5c5f7e4/lib/sass_spec/runner.rb#L44-L45) takes standard output, standard error, status, "clean" output and applies some very simple rules to determine if the test failed or succeeded. It currently does not use standard error, but it's there.

It seems to be trivial to add testing against std error, std output or both. You could even have something like "I want this in standard output and not this in standard error". The logic can be pretty arbitrary.

The only real issue is to specify **how** to express those rules. Something like:

1. If there is a `*testcase*.*outputstyle*.skip` file, please skip the test
1. If there is a `*testcase*.*outputstyle*.status` file, please match it against the status code returned. Stop checking further. (is it needed at all? probably not)
1. If there is a `*testcase*.*outputstyle*.error` file, please compare it against the standard error, fail if different. A zero-length `*testcase*.*outputstyle*.error` indicates the error output should be empty and no additional checks are to be made. Stop checking further if did a check here..
1. If there is a `*testcase*.*outputstyle*.clean` file, please perform the next test against a "cleaned" output.
1. If there is a `*testcase*.*outputstyle*.css` file, please compare it against the standard output.

plus checking of some flags. 

As I understand the ruby code right now, options 1, 4 and 5 are currently implemented.

There is also a possibility to generate "expected" output files with a command line option; we should decide the logic in which order those files are written, for example:
1. If the script generates some error output, write `.error` file. Stop.
2. If the script generates no error output, write stdout to the`.css` file.

As I understand the ruby code right now, option 2 is currently implemented.

So once we agree how to specify the expected error output, it should be trivial to implement.

**Comment by mgreter** [comment]
IMHO we just need someone to do the actual heavy lifting! I only fixed/updated about 5% of all error messages yet to conform to ruby sass! So there is another heavy lifting involved!

**Comment by saper** [comment]
I have a preliminary fix. My first ruby coding! :)

**Comment by saper** [comment]
comparing stacktraces will be a challenge. https://github.com/sass/libsass/pull/1555 just a tip of the iceberg :)

**Comment by saper** [comment]
First shot: https://github.com/sass/sass-spec/pull/494

**Comment by xzyfer** [comment]
@saper I've done some work to normalise Ruby Sass and LibSass error messages in https://github.com/sass-compatibility/sass-compatibility.github.io/blob/master/Rakefile#L94-L95

Might be of help.

**Comment by xzyfer** [comment]
@saper to be honest, as a first pass, just be able to assert that an error should have occurred and did it a big step. Currently when Ruby Sass error the spec fails which is the core problem.

Asserting the error message match can come later.

**Comment by saper** [comment]
@xzyfer Initially I wants to just test the status code, but it was so easy just to fix it all.

What is the proper incarnation of the test suite with Ruby Sass? I think I 70 failures using

`ruby sass-spec//sass-spec.rb -c ~/sw/sass/bin/sass --ignore-todo sass-spec`

This is on ruby sass stable 4ef8e31

**Comment by xzyfer** [comment]
That looks right, although you don't need --ignore-todo since there are technically no todos Ruby Sass. Those failure might be correct if you're using a newer version of Ruby than what's defined in the `Gemfile.lock`. A recent version of Ruby Sass change how it handle rounding in colour functions which a bunch for tests. That means the tests are correct as of the version defined in the Gemfile.

**Comment by saper** [comment]
I have went through [all error-test issues](https://github.com/sass/sass-spec/issues?utf8=%E2%9C%93&q=label%3Aerror-test), tested then under #494 and here are the results:


sass-spec pull req# | libsass issue# | ok with #494? | description 
--- | --- | ---- | ---
https://github.com/sass/sass-spec/pull/167 | https://github.com/sass/libsass/issues/713 | ✓
https://github.com/sass/sass-spec/pull/169 | https://github.com/sass/libsass/issues/698 |     | Message mismatch https://github.com/sass/libsass/issues/1558
https://github.com/sass/sass-spec/pull/261 | https://github.com/sass/libsass/issues/712 |     | Test fails - **reopen?**
https://github.com/sass/sass-spec/pull/276 | https://github.com/sass/libsass/issues/945 |  ✓
https://github.com/sass/sass-spec/pull/290 | https://github.com/sass/libsass/issues/871 |      | Test fails - **reopen?**
https://github.com/sass/sass-spec/pull/324 | https://github.com/sass/libsass/issues/1093 |    | Tests partially fail, **reopen?**. Also message problem #500 
https://github.com/sass/sass-spec/pull/373 | https://github.com/sass/libsass/issues/1187 |    | Message mismatch https://github.com/sass/libsass/issues/1561
https://github.com/sass/sass-spec/pull/404 | https://github.com/sass/libsass/issues/1266 |    | Message mismatch https://github.com/sass/libsass/issues/1559
https://github.com/sass/sass-spec/pull/451 | https://github.com/sass/libsass/issues/1355 | ✓
https://github.com/sass/sass-spec/pull/463 | https://github.com/sass/libsass/issues/1418 |    | Tests fail, **reopen?**
https://github.com/sass/sass-spec/pull/469 | https://github.com/sass/libsass/issues/1432 |    | Tests partially fail, **reopen?**. Also message mismatch https://github.com/sass/libsass/issues/1560
https://github.com/sass/sass-spec/pull/483 | https://github.com/sass/libsass/issues/1487 | ✓
https://github.com/sass/sass-spec/pull/486 | https://github.com/sass/libsass/issues/1484 | ✓

**Comment by saper** [comment]
https://github.com/sass/sass-spec/pull/502 brings tests formatted for #494 into the test suite. With #494 and #502 merged 100% of tests pass under Ruby Sass 3.4.14.2e0f33b as well as all tests that are not marked as **todo** pass with libsass.

**Comment by xzyfer** [comment]
@saper my preference would be that error message mismatches aren't considered failures for time being. To be quite honest we cannot match some of Ruby Sass error messages without a good chunk of work. 

I instead propose that an error test is successful if they both produce errors. Add a --strict flag for failing on error message mismatches. This allows us to continue moving forward without introducing regressions again and without losing a lot of time on exactly match error messages at the cost of feature work.

**Comment by saper** [comment]
Closed via #494. Thank you everyone!
