### ISSUE TITLE
The --unexpected-pass should take into account output styles

### ISSUE THREAD

**Issue by xzyfer** [sass/sass-spec#333]
The `--unexpected-pass` should consider a spec as unexpectedly passing, if and only if, all the output styles for that spec also pass.

**Comment by saper** [comment]
Every unit test should independent. Currently every output format variant constitutes a separate case. This means that even if we only check for an error or status code ( #494 ) we currently run 4 tests. Are there cases in real life when this matter? Because to implement this all output formats would need to became assertions in one test, which complicates things a bit.

**Comment by xzyfer** [comment]
Currently determining if a test has magically started passing is PITA.

IMHO the underlying sass spec data model is broken which makes these hard. We treat the entire spec as a single suite with 1000s of unit tests. Instead each spec folder should a suit and it's expected outputs as unit tests. If a single unit test fails that suite should fail. If a suite fails it's parent has failed etc..

**Comment by saper** [comment]
Note to self: sample problematic issues

spec/libsass-todo-tests/libsass/propsets
spec/libsass-todo-issues/issue_1026

**Comment by saper** [comment]
We no longer cater for different output styles.

**Comment by chriseppstein** [comment]
`--unexpected-pass` no longer exists. Use `--probe-todo` instead.
