### ISSUE TITLE
Test organization?

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass-spec#82]
@xzyfer mentioned the need for this on sass/libsass#521 — and I thought it deserved an issue over here. The current organization of sass-spec tests is quite difficult to sort through, based partially on what feature is being tested and partially on where support already exists.

I think the only organization that makes sense long-term is feature-based. Is there something stopping us from moving completely in that direction? Is there anything we can use as a "full list of features" to work against? Any inherent structure in the code, or somewhere in the RubySass project?

**Comment by chriseppstein** [comment]
I volunteer to reorganize these tests into features much like how @HugoGiraudel suggested. Some tests may need to be re-written, etc. The goal here is to have a clear approach to see how completely a engine implements a particular feature set and also going forward to know which tests are for new features that are being added to Sass.

Do you guys want me to go crazy or do you want to approve the work etc?

**Comment by xzyfer** [comment]
I think with a mix of feature and language (http://apps.workflower.fi/vocabs/css/en) based naming we can really clean up the specs. 

However my feeling atm is that the current state of sass-spec makes having an educated and productive discussion on the organisation of specs, and how sass spec fits into our workflow virtually impossible.

> Some tests may need to be re-written

This will almost certainly be the case. Many specs are snippets of code from the project that had the issue and aren't granular assertions of functionality.

> The goal here is to have a clear approach to see how completely a engine implements a particular feature set and also going forward to know which tests are for new features that are being added to Sass.

IMHO this plays into https://github.com/sass/sass/issues/1466. Ideally, for Libsass, new Sass features begin with a sass spec PR as a minimum viable RFC.

> Do you guys want me to just dig in or do you want to approve the work first?

Please feel free to tackle this on a branch and PR the results with a TLDR of the spec layout, and the workflow you envision.

Since we're currently working rapidly on 3.2.0, and 3.1.0 is about to hit the masses via node-sass@2.0.0 having sass-spec changing under our feet (read: on master) is going to be problematic.

**Comment by HugoGiraudel** [comment]
As I said to @chriseppstein last night, I am fully okay to help with the new test organisation. I would probably suggest we tackle things this way:

1. Move all tests to a `spec/todo/` folder or whatever.
1. For each test, try to find it a generic parent suite collection (`strings`, `mixins`, `variables`, `scope`, `at-root`...) then try to find it a meaningful name.
1. Move it to `spec/{{ <generic_parent_suite_collection> }}/{{ <meaningful_test_name> }}` (we could also have more than 2 levels if needed).
1. Repeat step 2 and 3 until all tests have been moved.

Also, since we do not want to lose relations between tests and issues, I propose we have normalized comments within the `input.scss` files for that. Unless I have been mistaken, @chriseppstein kind of agreed on this but I suppose we should have over opinions as well.

Obviously, such comments should be normalized so they all look alike, are easily written, read and parsed if ever needed. May I suggest something like this:

```scss
// @issue https://github.com/sass/libsass/issues/42
// @issue https://github.com/sass/libsass/issues/1337
```

I do not think there should be a limit to the number of annotation we could put on top, as long as they are relevant. This way, it would be fairly easy to find an issue from within the spec folder. Just head to specific test (which should be easy to do given we would organize them with meaningful folder names), then go the mentioned link.

Any thoughts?

**Comment by hcatlin** [comment]
I'll answer @chriseppstein with a resounding... GO FOR IT!

The Ruby test driver is shitty code that was meant to get refactored. I think one of the original versions was done by a very junior developer, and it shows. Just, FYI. :P

**Comment by chriseppstein** [comment]
I will keep my progress on a branch so that we can land it at an appropriate time -- and I will be testing it against  sass and libsass as I go.

**Comment by mgreter** [comment]
Are you planning to support different output styles? I?m in the process of getting libsass ready to have the output mapped 1:1 to ruby sass (I already have it working for all but 7 cases, which I'm currently working at). I currently use the fallowing structure in my local perl-libsass test runner:

```
config
input.s[ac]ss
output.nested.css
output.nested.css.map
output.nested.css.err
output.compressed.css
output.compressed.map
output.compressed.err
```

I guess this task here is mostly about structuring the tests themselve and I can re-genarate the output files automatically. Just wanted to ask if it is planned to support testing different output styles and also different options (which is what the `config` file is doing).

**Comment by chriseppstein** [comment]
I'm going to close this. we have the structure we have for 3.4. In future Sass versions, I will make sure the specs are organized by feature.
