### ISSUE TITLE
Error in 3.5 specification related to the expected value after finding an unmatched right square bracket

### ISSUE THREAD

**Issue by delapuente** [sass/sass-spec#907]
According to [current specification](https://github.com/sass/sass-spec/blob/master/spec/sass_3_5/custom_properties/error/unmatched_brackets/square/error), it says the expected output should be:

```
Error: Invalid CSS after "  --prop: [{": expected "}", was "];"
```

But that is incorrect since what we are expecting is an expression. Something more like:

```
Error: Invalid CSS after "  --prop:": expected expression (e.g. 1px, bold), was "];"
```

**Comment by nex3** [comment]
This error message is correct. Within the context of a custom property, there's no such thing as "an expression"; custom properties are extremely permissive about their values, to the extent that they're essentially a sequence of arbitrary characters with very few restrictions. One of the only restrictions that does exist is that brackets must be properly nested, so that's what this error describes.
