### ISSUE TITLE
Include SourceMap tests

### ISSUE THREAD

**Issue by nschonni** [sass/sass-spec#920]
I was looking at the cleaning up the node-sass test suite, but realized we need to keep our sourcemap tests right now.
What do you think of including sourcemaps for the `expected.css`? Also maybe some `option.yml` frontmatter to cover the other sourcemap options (inline, relative, etc..)?

**Comment by xzyfer** [comment]
We have some issues in LibSass with regards to sourcemap being different. We have some hacks targeted at making Chrome behaviour. No browser follows the full sourcemaps spec, current implementations are varying degrees of under baked.

Sass spec has a very limited scope. It's job is to assert the semantic equality of output CSS of different engines. Currently we do exact output + some normalisation. This is just because there isn't a good prebuilt library for assert semantic equality of CSS. 

This is also the reason we've recently moved output style spec off to the side. The insignificant whitespace in output styles doesn't affect semantic equality.

For this reason I don't think it's reasonable to expect implementations to agree on sourcemaps. IMHO this is out of scope for sass spec in the same way output formats are.

**Comment by nschonni** [comment]
> We have some issues in LibSass with regards to sourcemap being different.

This should be fixed if https://github.com/sass/sass/pull/2150 and https://github.com/sass/libsass/pull/2193 land.

**Comment by xzyfer** [comment]
I don't believe that's true. The sourcemaps generated by LibSass are structurally different mapping. I'm still of the opinion this does not belong in sass spec.

**Comment by nex3** [comment]
I agree with @xzyfer. How each implementation handles source maps is up to that implementation, and not something that should be mandated by sass-spec.
