### ISSUE TITLE
Run specs against expanded mode by default

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#944]
Currently the bulk of the specs are written in nested mode, which is generally pretty unpopular. New implementations may not even want to implement it. Expanded mode is more common and more in line with standard CSS style; it should be the default, and only specs that specifically intend to exercise style support should be defined against other styles.

**Comment by nschonni** [comment]
I agree that it is probably easier to read, but are you going to change the language default too http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
If so, it should be just a matter of regenerating the tests. Otherwise, it's still doable, just need to change the runner defaults and then regenerate everything.

**Comment by nex3** [comment]
I'm not sure if we'll change the executable default—it seems like more hassle than it's worth. But we could consider it.

**Comment by xzyfer** [comment]
I support this ❤️  I see a world where LibSass only supports expanded and compressed outputs.

**Comment by nschonni** [comment]
> I support this  I see a world where LibSass only supports expanded and compressed outputs.

Now would probably be the right time, because you could depricate it in 3.5, and then remove it in 4.0.

**Comment by xzyfer** [comment]
I think it's too early for that. It's still just a thought.
