### ISSUE TITLE
Use the options.yml for TODO flagged tests

### ISSUE THREAD

**Issue by nschonni** [sass/sass-spec#950]
Instead of moving tests around from folder to folder for the todo (mostly libsass right now), what if we just create create the simple `options.yml` in the individual spec folder? Then the flag to remove the test would either update the `options.yml` file to remove the specific todo, or delete the file if it had no further values in the Yaml.

**Comment by xzyfer** [comment]
We've done this for new features. This has come up before, and the LibSass team rallied to keep the current workflow because it gives us a way to gauge how much work we have to do at a glance. Another argument for keep the current libsass-todo-* folder has been that noone has the time to move the specs into the appropriate place. This would require someone to dedicate significant time to organising the specs into logical groups.

This is arguably less relevant in a post LibSass 3.4 world. All new 3.5 specs have been added as this issue suggests.

**Comment by mgreter** [comment]
Not sure about this, as it obfuscates which issues are still open for libsass. IMO we must have at least some way to query the open todos before considering this. I really like that I can just browse those two folders to see which kind of issues are not solved yet. And I think it doesn't really make a difference if we move files or edit the options.yml, we need to make a commit either way (I would even argue that moving is easier and less error prone than editing options.yml).

**Comment by nex3** [comment]
I'd also really like a way to query various stats about the number of tests with various sorts of configurations.

**Comment by nschonni** [comment]
I'm thinking the report and other stats stuff might need to be split out of the [annotate](https://github.com/sass/sass-spec/blob/master/lib/sass_spec/annotate/cli.rb)

**Comment by stof** [comment]
@nex3 @jathak I suggest closing this issue, as marked tests as TODO is handled by the options since years now.
